### ISSUE TITLE
Impossible to launch on Windows

### ISSUE THREAD

**Issue by wolicodes** [RedHatter/nms-sort-o-matic#2]
I have this error when I try to launch the program.

The `d862dd7f6518018f492a5d982f4302e542ddf9d485b8c89f460321e0652e58a0 ` folder doesn't exist on my machine.

`pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: C:\Users\xxx\AppData\Local\Temp\pkg\d862dd7f6518018f492a5d982f4302e542ddf9d485b8c89f460321e0652e58a0\lz4\build\Release\xxhash.node is not a valid Win32 application.
C:\Users\xxx\AppData\Local\Temp\pkg\d862dd7f6518018f492a5d982f4302e542ddf9d485b8c89f460321e0652e58a0\lz4\build\Release\xxhash.node
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
←[90m    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:988:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:834:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1012:19)←[39m
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\snapshot\nms-sort-o-matic\node_modules\←[4mlz4←[24m\lib\utils.js:4:11)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)←[39m {
  code: ←[32m'ERR_DLOPEN_FAILED'←[39m
}

Node.js v18.5.0
Press any key to continue . . .`

**Comment by RedHatter** [comment]
Fixed in version [0.4.0](https://github.com/RedHatter/nms-sort-o-matic/releases/tag/v0.4.0)
